package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"
	pb "greeting/proto"
)

// Greet is the resolver for the greet field.
func (r *mutationResolver) Greet(ctx context.Context, input Request) (*Response, error) {
	req := &pb.Request{Req: input.Req}
	res, err := r.Client.Greet(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("error in gRPC call: %s", err)
	}
	return &Response{Res: &res.Res}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
